apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-deployment
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: myproject2
        image: ritussharma/website
        ports:
        - containerPort: 80
